---
__ec2_id_name: "{{ ec2_id_name }}"
__ec2_vpc_subnet_id: "{{ ec2_vpc_subnet_id }}"
__ec2_security_group_name: "{{ ec2_security_group_name }}"

__ec2_assign_public_ip: "{{ __ec2_assign_public_ip | default('true') }}"
__ec2_ami_id: "{{ ec2_ami_id | default('ami-02c86bb8afb45cdeb') }}"
__ec2_instance_type: "{{ ec2_instance_type | default('t2.micro') }}"
__ec2_keypair_name: "{{ ec2_keypair_name | default('kedwards_keca') }}"
__ec2_region: "{{ ec2_region | default('ca-central-1') }}"
__ec2_tag_env: "{{ ec2_tag_env | default('dev') }}"
__ec2_tag_owner: "{{ ec2_tag_owner | default('kedwards') }}"
