---
- name: Find enabled sites
  shell: ls -1 {{ __nginx_conf_dir }}/sites-enabled || true
  register: enabled_sites
  changed_when: false

- name: Disable unmanaged sites
  file:
    path: "{{ __nginx_conf_dir }}/sites-enabled/{{ item }}"
    state: absent
  with_items: "{{ enabled_sites.stdout_lines | default([]) }}"
  when: item[:-5] not in __nginx_sites.keys()
  # notify:
  #   - reload nginx
