---
- set_fact:
    __from_template: "{{ lookup('template', './security.j2') }}"
  vars:
    __to_template_vpc_security_groups: "{{ __vpc_security_groups }}"

- name: Provision EC2 security groups
  no_log: true
  ec2_group:
    state: present
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    vpc_id: "{{ my_ec2_vpc_net.vpc.id }}"
    region: "{{ item.region }}"
    rules: "{{ item.rules }}"
    rules_egress: "{{ item.rules_egress }}"
    tags:
      Name:  "{{ item.name }}"
      Service: ec2_group
      Env: "{{ __vpc_tag_env }}"
      Owner: "{{ __vpc_tag_owner }}"
      Created: "{{ lookup('pipe', 'date +%Y%m%d') }}"
      Expired: "{{ lookup('pipe', 'date -d \"1 year\" +\"%Y%m%d\"') }}"
  with_items: "{{ __from_template.vpc_security_groups }}"
  register: my_ec2_group
