---
- name: Discover Services
  shell: ansible -i inventory vp_app,ew_app -m mrm_cfg
  args:
    chdir: ~/workspace/ansible-openlink/
  register: services_data
  delegate_to: 127.0.0.1
  no_log: true
  run_once: true

- name: Write Service file
  copy:
    content: "{{ services_data.stdout }}"
    dest: "{{ role_path }}/data/services_status_raw.json"
  delegate_to: 127.0.0.1
  run_once: true

- name: Process Service file
  shell: php run.php
  args:
    chdir: "{{ role_path }}/scripts/"
  delegate_to: 127.0.0.1
  no_log: true
  run_once: true

- name: Deploy Report
  win_copy:
    src: "{{ role_path }}/files/services_status.json"
    dest: D:\inetpub\wwwroot\service-report\res\data\services_status.json
