---
- ec2_metadata_facts:
  register: __route53_ec2_facts

- set_fact:
    __route53_ipv4_value: "{{ __route53_ec2_facts.ansible_facts.ansible_ec2_public_ipv4 }}"

- name: Add EC2 instance to route53
  route53:
    state: present
    aws_access_key: "{{ __route53_aws_access_key }}"
    aws_secret_key: "{{ __route53_aws_secret_key }}"
    overwrite: true
    zone: "{{ item.value.domain }}"
    record: "{{ item.value.fqdn }}"
    type: "{{ item.value.type }}"
    ttl: "{{ item.value.ttl }}"
    value: "{{ __route53_ipv4_value }}"
  with_dict: "{{ __route53_routes }}"
  register: my_route53
