---
- name: Provision EC2 instance
  ec2:
    image: "{{ __ec2_ami_id }}"
    instance_type: "{{ __ec2_instance_type }}"
    assign_public_ip: true
    key_name: "{{ __ec2_keypair_name }}"
    region: "{{ __ec2_region }}"
    vpc_subnet_id: "{{ __ec2_vpc_subnet_id }}"
    id: "{{ __ec2_id_name }}"
    exact_count: 1
    wait: yes
    group: "{{ __ec2_security_group_name }}"
    instance_tags:
        Name: "{{ __ec2_id_name }}"
        Service: ec2
        Env: "{{ __ec2_tag_env }}"
        Owner: "{{ __ec2_tag_owner }}"
        Created: "{{ lookup('pipe', 'date +%Y%m%d') }}"
        Expired: "{{ lookup('pipe', 'date -d \"1 year\" +\"%Y%m%d\"') }}"
    count_tag:
      Name: "{{ __ec2_id_name }}"
  register: my_ec2
