---
- name: Find config files
  shell: find {{ __nginx_conf_dir}}/conf.d -maxdepth 1 -type f -name '*.conf' -exec basename {} \;
  register: config_files
  changed_when: false

- name: Remove unmanaged config files
  file:
    name: "{{ __nginx_conf_dir }}/conf.d/{{ item }}"
    state: absent
  with_items: "{{ config_files.stdout_lines | default([]) }}"
  when: item[:-5] not in __nginx_configs.keys()
