---
- name: Disable the default site
  file:
    path: "{{ __nginx_conf_dir }}/sites-enabled/default"
    state: absent

- name: Remove the default configuration
  file:
    path: "{{ __nginx_conf_dir }}/conf.d/default.conf"
    state: absent
  when: >
    'default' not in __nginx_configs.keys()

# - name: Reload Nginx
#   notify:
#     - reload nginx
