---
- name: install Server Config File
  become: yes
  template:
    src: server.cnf.j2
    dest: "{{ mariadb_config_server }}"

- name: install Network Config File
  become: yes
  template:
    src: network.cnf.j2
    dest: "{{ mariadb_config_network }}"

- name: install Custom Config File
  become: yes
  template:
    src: custom.cnf.j2
    dest: "{{ mariadb_config_custom }}"
  when: mariadb_custom_cnf|length != 0

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: "{{ mariadb_swappiness }}"
    state: present
  when: mariadb_configure_swappiness

- name: Ensure service is started
  service:
    name: "{{ mariadb_service }}"
    state: started
    enabled: true
