---
# join the remaining workers to the swarm cluster
- name: join worker nodes to cluster
  shell: >
    docker swarm join
    --advertise-addr={{ swarm_iface | default('eth1') }}:2377
    --token={{ hostvars[groups['swarm_manager_operational'][0]]['swarm_worker_token']['stdout'] }}
    {{ groups['swarm_manager_ips'][0] }}:2377
  when: inventory_hostname in groups['swarm_worker_bootstrap']
