---
region: us-east-1
instance_type: t2.nano
# ami: ami-f4cc1de2  # Ubuntu 16.04 LTS
ami: ami-49c9295f  # Ubuntu 14.04 LTS
project_name: testing
env: staging
app_code_user: "ubuntu" # remote user
hoststring: "ansible_ssh_user=ubuntu ansible_ssh_private_key_file=../aws-private.pem"
hostpath: "../hosts"

region: ca-central-1
instance_type: t2.nano
ami: ami-00e4c0aa1e3fce5e8  # Debian GNU/Linux 9.5+1 (Stretch)
keypair: ke.ca # pem file name
vpc_subnet: subnet-b5f03ddc
security_group: web-sg-001 # security group name

env: staging
user: "admin" # remote user
hoststring: "ansible_ssh_user=admin ansible_ssh_private_key_file=../keca.pem"
hostpath: "../hosts"
