---
- name: Create the directories for site specific configurations
  file:
    path: "{{  __nginx_conf_dir }}/{{ item }}"
    state: directory
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_group }}"
    mode: "{{ __nginx_dir_perm }}"
  with_items:
    - sites-available
    - sites-enabled
    - auth_basic
    - conf.d
    - conf.d/stream
    - snippets
    - modules-available
    - modules-enabled

- name: Ensure log directory exist
  file:
    path: "{{ __nginx_log_dir }}"
    state: directory
    owner: "{{ __nginx_log_user }}"
    group: "{{ __nginx_log_group }}"
    mode: "{{ __nginx_log_perm }}"
