---
- name: Configure IP forwarding
  sysctl:
    state: present
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/nat.conf
    sysctl_set: yes
    reload: yes
  with_items:
    - { name: net.ipv4.ip_forward, value: 1 }
    - { name: net.ipv4.conf.eth0.send_redirects, value: 0 }
