---
- name: Ensure docker-machine is installed and available
  get_url:
    url: "https://github.com/docker/machine/releases/download/{{ version }}/docker-machine-{{ ansible_system }}-{{ ansible_userspace_architecture }}"
    dest: /usr/local/bin/docker-machine
    mode: 'a+x'

    