---
- name: Update the apt package index
  apt:
    name: "*"
    state: latest
    update_cache: yes
    force_apt_get: yes

- name: Install packages
  apt:
    name: "{{ packagesdep }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  vars:
    packagesdep:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
