---
- name: Add Apt signing key from official docker repo
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker official repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ version }} stable
    state: present

- name: Install packages
  apt:
    name: "{{ packagesdep }}"
    force_apt_get: yes
    state: latest
    update_cache: yes
  vars:
    packagesdep:
      - docker-ce
      - docker-ce-cli
      - containerd.io