---
- name: add Name and service to tag dict
  set_fact:
    merged_tags: "{{ merged_tags | combine({item.key: item.value}) }}"
  with_items:
    - { key: Name, value: "{{ vpc_igw_name }}" }
    - { key: Service, value: ec2_vpc_igw }

- name: create Internet Gateway
  ec2_vpc_igw:
    state: present
    vpc_id: "{{ my_ec2_vpc_net.vpc.id }}"
    region: "{{ vpc_region }}"
    tags: "{{ merged_tags }}"
  register: my_ec2_vpc_igw
