---
- name: add Name and service to tag dict
  set_fact:
    merged_tags: "{{ merged_tags | combine({item.key: item.value}) }}"
  with_items:
    - { key: Name, value: "{{ vpc_ec2_nat_name }}" }
    - { key: Service, value: ec2_vpc_igw }

- name: create Nat Instance
  ec2:
    image: "{{ vpc_ec2_image_id }}"
    instance_type: "{{ vpc_ec2_instance_type }}"
    key_name: "{{ vpc_ec2_keypair_name }}"
    region: "{{ vpc_region }}"
    zone: "{{ vpc_az1 }}"
    network_interfaces: "{{ my_ec2_eni.interface.id }}"
    id: "{{ vpc_ec2_nat_name }}"
    source_dest_check: no
    exact_count: 1
    wait: yes
    instance_tags: "{{ merged_tags }}"
    count_tag:
      Name: "{{ vpc_ec2_nat_name }}"
  register: my_nat_ec2
