---
- ec2_metadata_facts:
  register: __route53_ec2_facts

- set_fact:
    __route53_value: "{{ __route53_ec2_facts.ansible_facts.ansible_ec2_public_ipv4 }}"

- name: Add EC2 instance to route53
  route53:
    state: present
    aws_access_key: AKIAJZS3JM2OO6E32QSQ
    aws_secret_key: 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
    zone: "{{ __route53_domain }}"
    record: "{{ __route53_fqdn }}"
    type: "{{ __route53_type }}"
    ttl: "{{ __route53_ttl }}"
    value: "{{ __route53_value }}"
    wait: yes
  register: my_route53
