---
- name: Ensure aws-vault is installed and available
  get_url:
    url: "https://github.com/99designs/aws-vault/releases/download/{{ version }}/aws-vault-linux-amd64"
    dest: /usr/local/bin/aws-vault
    mode: 'a+x'