---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: ROLENAME

- import_tasks: configure/host.yml

- import_tasks: configure/route53.yml

- import_tasks: configure/route53.yml
  vars:
    - route53_host: www
    - route53_domain: kevinedwards.ca
    - route53_type: CNAME
