---
- name: Ensure nginx_vhost_path exists.
  file:
    path: "{{ __nginx_vhost_path }}"
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_group }}"
    mode: "{{ __nginx_dir_perm }}"
    state: directory

- name: Create the vhost configurations
  template:
    src: "{{ item.value.template | default(__nginx_default_site_template) }}"
    dest: "{{ __nginx_conf_dir }}/sites-available/{{ item.key }}.conf"
    backup: yes
  with_dict: "{{ __nginx_sites }}"
  when: item.key not in __nginx_remove_sites

- name: Create links for sites-enabled
  file:
    state: link
    src: "{{ __nginx_conf_dir }}/sites-available/{{ item.key }}.conf"
    dest: "{{ __nginx_conf_dir }}/sites-enabled/{{ item.key }}.conf"
  with_dict: "{{ __nginx_sites }}"
  when: (item.key not in __nginx_remove_sites) and (item.key not in __nginx_disabled_sites)

- name: Create the directories for vhosts
  file:
    path: "{{  __nginx_vhost_path }}/{{ item.key }}"
    state: directory
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_group }}"
    mode: "{{ __nginx_dir_perm }}"
  with_dict: "{{ __nginx_sites }}"

- name: Create defaut html pages for vhosts
  template:
    src: "{{ __nginx_index_php_template }}"
    dest: "{{ __nginx_vhost_path }}/{{ item.key }}/index.php"
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_group }}"
    mode: "{{ __nginx_file_perm }}"
  with_dict: "{{ __nginx_sites }}"

- name: Create defaut php pages for vhosts
  template:
    src: "{{ __nginx_index_html_template }}"
    dest: "{{ __nginx_vhost_path }}/{{ item.key }}/index.html"
    owner: "{{ __nginx_user }}"
    group: "{{ __nginx_group }}"
    mode: "{{ __nginx_file_perm }}"
  with_dict: "{{ __nginx_sites }}"

- name: Create links for website root
  file:
    state: link
    src: "{{ __nginx_vhost_path }}/{{ item.key }}"
    dest: "/var/www/{{ item.key }}"
  with_dict: "{{ __nginx_sites }}"
  when: (item.key not in __nginx_remove_sites) and (item.key not in __nginx_disabled_sites)
